version: "3"

services:
  postgres:
    image: "postgres:11.5"
    environment:
      - "POSTGRES_USER=trab"
      - "POSTGRES_DB=trab"
      - "POSTGRES_PASSWORD=trab"
    expose:
      - "5432"
    ports:
      - "5432:5432"